## 输出层的设计
神经网络可以用在分类问题和回归问题，需要根据情况改变输出层的激活函数。
回归问题用恒等函数，分类问题用softmax函数。

**机器学习的问题大致氛围分类问题和逻辑回归问题。分类问题是数据属于哪一类的问题。如，区分图像中的人是男性还是女性的问题就是分类问题。而回归问题是根据某个输入预测一个（连续）的数字问题，比如根据一张图片预测一个人的体重问题就是回归问题**

### 恒等函数和softmax函数
恒等函数会将输入按照原样输出，对于输入的信息，不加任何改动的直接输出。
因此输出层使用恒等函数时数据会被原封不动的输出。
#### 恒等函数
分类问题中使用softmax函数可以用下面的式子表示
$$
y_k =\frac{exp(a_k)} {\sum_{i=1}^n exp(a_i)}
$$
### softmax的实现

In [1]:
import numpy as np

a = np.array([0.3,2.9,4.0])
exp_a=np.exp(a) #指数函数
print(exp_a)
sum_exp_a= np.sum(exp_a) #求和
print(sum_exp_a)
y = exp_a/sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


定义为python函数softmax()

In [2]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a= np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

### 实现softmax时的注意事项
因为使用指数函数，这个值会被变大。所以会出现溢出的情况
以下改进softmax函数
$$
\begin{aligned}
y_k &=\frac{exp(a_k)} {\sum_{i=1}^n exp(a_i)}\\
&= \frac{C exp(a_k)} {\sum_{i=1}^n C exp(a_i)}\\
&= \frac{exp(a_k+logC)} {\sum_{i=1}^n exp(a_i+logC)}\\
&= \frac{exp(a_k+C^')} {\sum_{i=1}^n exp(a_i+C^')}
\end{aligned}
$$

In [3]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c) # 溢出策略
    sum_exp_a= np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

a = np.array([0.3,2.9,4.0])
y=softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0


### softmax函数的特征
softmax函数的输出是0.0到1.0之间的实数。并且输出的总和为1是softmax函数的一个性质。
把函数的输出概率解释为"概率"
也就是说，通过使用softmax函数。
即便使用了softmax函数，各个元素之间的大小关系也不会改变。因为指数函数是单调递增的函数。
输入a元素的大小关系和输出y的大小关系也没有改变
神经网络只是把最大的神经元所对应的类别作为识别结果。
因此在神经网络进行分类时。输出层的softmax函数可以省略。
在实际的问题中指数运算需要一定的运算量。因此输出层的softmax函数一般会被省略。
- 求解机器学习问题的步骤可以分为"学习"和"推理"。首先在学习阶段进行模型的学习。然后再推理阶段，用学到的模型对位置的数据进行推理分类。
- 推理阶段一般会省略输出层的softmax函数。在输出层使用softmax函数是因为softmax函数和神经网络的学习有关
### 输出层的神经元数量
输出层的神经元数量需要根据待解决的问题来决定。对于分类问题，输出层的神经元数量一般设定为类别的数量