## 多维数组的运算
### 多维数组
获取维数通过np.ndim()函数获得
数组的形状通过np.shape()函数获得
二维数组也称为矩阵(matrix)。
数组的横向排列称为行(row)，纵向排列称为列(column)。

In [330]:
import numpy as np

A = np.array([1, 2, 3, 4])
B = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(B)
print(np.ndim(A))  #获取维数
print(np.ndim(B))  #获取维数
print(np.shape(A))  #获取形状
print(np.shape(B))  #获取形状



[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
1
2
(4,)
(3, 2)


### 矩阵乘法
 $2×3$的矩阵和$3 × 2$的矩阵的乘积实现

In [331]:
A = np.array([[1, 2, 3]
                 , [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2]
                 , [3, 4]
                 , [5, 6]])
print(B.shape)
C = np.dot(A, B)
print(C)
print(C.shape)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
(2, 2)


矩阵的乘积运算中，对应维度的元素个数要保持一致

### 神经网络的内积
使用NumPy矩阵来实现神经网络。

In [332]:
X = np.array([1, 2])
W = np.array([[1, 3, 5], [2, 4, 6]])
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


神经网络的晕眩可以作为矩阵运算打包进行。因为神经网络各层的运算是通过矩阵乘法运算打包进行的。
权重和隐藏层的神经元的右上角有一个(1)，表示权重和神经元的层号
右下角的两个数字，是后一层神经元和前一层神经元的索引号。
$w_{{1}~{2}}^{(1)}$表示前一层的第2个神经元$x_2$到后一层的第一个神经元$a_1^{(1)}$的权重。
权重右下角按照后一层的索引号，前一层的索引号的顺序排列


### 各层之间信号传递的实现
$a_{{1}}^{(1)}$=$w_{{1}~{1}}^{(1)}$$x_1$+$w_{{1}~{2}}^{(1)}$$x_2$+$b_{{1}}^{(1)}$
如果使用矩阵乘法运算，则可以将第一层的加权和表示层下面的式子。
$$
 A^{(1)}=XW^{(1)}+B^{(1)}
$$
$A_{(1)}$,$X$,$B_{(1)}$,$W_{(1)}$表示：
$$
A_{(1)}=\bigl(
    \begin{matrix}
		a_{{1}}^{(1)}& a_{{2}}^{(1)}& a_{{3}}^{(1)}
	\end{matrix}
\bigr)$ ~,~ X=$\bigl(
    \begin{matrix}
		x_1&x_2
	\end{matrix}
\bigr)
$$

$$
B_{(1)}=\bigl(
    \begin{matrix}
		b_1^{(1)}&b_2^{(1)}&b_3^{(1)}
	\end{matrix}
\bigr)
$$
$$
W_{(1)}=
    \begin{pmatrix}
		w_{{1}~{1}}^{(1)}&w_{{2}~{1}}^{(1)}&w_{{3}~{1}}^{(1)} \\
        w_{{1}~{1}}^{(2)}&w_{{2}~{2}}^{(1)}&w_{{3}~{2}}^{(1)}
	\end{pmatrix}

$$
以下使用NumPy多维数组来实现
### 从输入层到第1层的信号传递

In [333]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


X = np.array([1.0, 0.5])  # 输入
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])  # 权重
B1 = np.array([0.1, 0.2, 0.3])  #偏置
A1 = np.dot(X, W1) + B1
print(A1)
Z1 = sigmoid(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]



### 实现第1层到第2层的信号传递


In [334]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])  #权重
B2 = np.array([0.1, 0.2])  #偏置
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


### 第二层到输出层的基本实现

In [335]:
def identity_function(x):
    return x


W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
print(Y)

[0.31682708 0.69627909]


这里定义identity_function()函数，也称为"恒等函数"，并将其作为输出层的激活函数。恒等函数会将输入按照原样输出。
输出层的激活函数用$\sigma()$表示，不同于隐藏层的激活函数$h()$使用的为sigmoid()函数。

- 输出层所用的激活函数根据求解问题的性质决定。一般回归问题使用恒等函数。二元分类问题使用sigmoid函数，多元分类问题使用softmax函数。

---------

### 三层神经网络的代码实现

In [336]:
def init_network():
    network = {  #定义字典
        'W1': np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]), #权重
        'b1': np.array([0.1, 0.2, 0.3]), # 偏置
        'W2': np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]]),
        'b2': np.array([0.1, 0.2]),
        'W3': np.array([[0.1, 0.3], [0.2, 0.4]]),
        'b3': np.array([0.1, 0.2])

    }
    return network


def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    return y


network = init_network()
x = np.array([1.0, 0.5]) # 输入信号
y = forward(network, x)
print(y)


[0.31682708 0.69627909]
